CREATE TABLE address (
	zipcode varchar(20) NOT NULL,
	street varchar(50) NOT NULL,
	box_number varchar(30) NOT NULL,
	city varchar(40) NULL,
	address2country int8 NOT NULL,
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT address_pk PRIMARY KEY (id)
);


-- public.address foreign keys

ALTER TABLE address ADD CONSTRAINT address_address2country_fkey FOREIGN KEY (address2country) REFERENCES country(id);