-- public.company definition

-- Drop table

-- DROP TABLE public.company;

CREATE TABLE public.company (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(40) NOT NULL,
	company2address int8 NOT NULL,
	CONSTRAINT company_pk PRIMARY KEY (id)
);


-- public.company foreign keys

ALTER TABLE public.company ADD CONSTRAINT company_company2address_fkey FOREIGN KEY (company2address) REFERENCES public.address(id);