-- public.contact definition

-- Drop table

-- DROP TABLE public.contact;

CREATE TABLE public.contact (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	lastname varchar(40) NOT NULL,
	firstname varchar(40) NOT NULL,
	contact2address int8 NOT NULL,
	CONSTRAINT contact_pk PRIMARY KEY (id)
);