-- public.country definition

-- Drop table

-- DROP TABLE public.country;

-- post gre
CREATE TABLE public.country (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	iso_3_code varchar(3) NOT NULL,
	"name" varchar(50) NOT NULL,
		active bit DEFAULT 1 NOT NULL,
	CONSTRAINT country_pk PRIMARY KEY (id)
);

-- sql 
CREATE TABLE country (
	id INT IDENTITY(1,1),
	iso_3_code varchar(3) NOT NULL,
	name varchar(50) NOT NULL,
		active bit DEFAULT 1 NOT NULL,
	CONSTRAINT country_pk PRIMARY KEY (id)
);

