-- public.country definition

-- Drop table

-- DROP TABLE public.country;

CREATE TABLE public.country (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	iso_3_code varchar(3) NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT country_pk PRIMARY KEY (id)
);