version: '3.4'

services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "5000:80"
  sqldb:
    container_name: sql_server2019
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Semlex_753"
        ACCEPT_EULA: "Y"